### ISSUE TITLE
Use of old version of android SDK and Kotlin plugin.

### ISSUE THREAD

**Issue by letsintegreat** [PranshuPandya/locus-stolker-app#13]
The current `compileSdkVersion` is set to 30, which is not compatible with one of the dependencies, and hence raising an error while building the project for android.

Here is the error message: https://pastebin.com/2skBHszR

Also, the current kotlin version is set to `1.3.50` which is an old version and is causing problems while building.

**Comment by letsintegreat** [comment]
I'd like to work on this issue.

**Comment by PranshuPandya** [comment]
Ok I am assigning you this issue. Make sure you create a separate branch for this.
