### ISSUE TITLE
Improving overall UI of app

### ISSUE THREAD

**Issue by PranshuPandya** [PranshuPandya/locus-stolker-app#2]
currently the ui is very basic so we need to improve that.

**Comment by TESLA2402** [comment]
can I solve this issue?

**Comment by PranshuPandya** [comment]
ya go ahead.

**Comment by PranshuPandya** [comment]
> can I solve this issue?

I have merged your recent pull request but I would love if you could make it uniform like currently it is random mix of black, white, teal . if you don't want to work on it anymore than its completely fine it is really a tough one and it will take some thought and work.

**Comment by TESLA2402** [comment]
Yeah sure but I am not that good at designing UI but if I get some  better thoughts regarding it  I will definitely work on that .
Will I get some points for that previous merged PR?

**Comment by PranshuPandya** [comment]
Ya I am giving you 5 points for your time. but I will like to give you the full 20 point and some bonus if you come up with an excellent UI

**Comment by Anirudha0789** [comment]
Can I work on it?

**Comment by Pranav108** [comment]
@PranshuPandya Can I take this issue?

**Comment by Pranav108** [comment]
@PranshuPandya  are you okay with something like this?
<img src="https://user-images.githubusercontent.com/56934594/145961475-0c07886c-4e8d-4d22-a8c9-4b744636b690.png" alt="drawing" width="400"/>

**Comment by PranshuPandya** [comment]
ya looks good
