### ISSUE TITLE
need improvement in depreacted widgets

### ISSUE THREAD

**Issue by Pranav108** [PranshuPandya/locus-stolker-app#22]
Throughout the code in some places FlatButton widget is used (e.g. in group_member.dart, search_screen_dart) which is 
 now deprecated and we have now alternate widget for them.
These widgets needs to improved to their latest alternate option.

**Comment by TESLA2402** [comment]
can I solve this issue?

**Comment by PranshuPandya** [comment]
> can I solve this issue?

you are already assigned an issue right? wait for a while, if someone else want to contribute.

**Comment by samyakjain26** [comment]
assign me this issue please

**Comment by PranshuPandya** [comment]
ya sure

**Comment by TESLA2402** [comment]
Hey! can I work on this issue now?
