### ISSUE TITLE
Linking the links to linkdin app 

### ISSUE THREAD

**Issue by PranshuPandya** [PranshuPandya/locus-stolker-app#3]
In the about page in contact us add feature so that on clicking the link the profile gets open in the linkedin app.

**Comment by Pranav108** [comment]
Though I'm a beginner but I would love to work on it, can you please assign it to me?

**Comment by PranshuPandya** [comment]
ya sure.

**Comment by PranshuPandya** [comment]
nice work adding 25 points ( 20 as it was hard and 5 bonus points)
