### ISSUE TITLE
Add Pull Request template

### ISSUE THREAD

**Issue by pushkar2112** [PranshuPandya/locus-stolker-app#30]
The project does not have a PR template.
Should look something like -

## Issue
Fixes #(Mention the issue ID here)

## Checklist
- [ ] The app builds properly
- [ ] Code is commented in difficult to understand areas
- [ ] Code is formatted well

**Comment by pushkar2112** [comment]
I would like to work on this.

**Comment by PranshuPandya** [comment]
If no one come up I will assign it to you as you already have an issue assigned wait for some time.

**Comment by Vaibhav-Chopra-GT** [comment]
Can I work on this issue?
