### ISSUE TITLE
Overflow of widgets on search screen

### ISSUE THREAD

**Issue by Pranav108** [PranshuPandya/locus-stolker-app#37]
# Description
Some widget of search_screen overflow by some pixels. This occurs on my 720 x 1560 pixels physical device. 

# Relevant files
lib\screens\search_screen.dart

# Screenshot
<img src="https://user-images.githubusercontent.com/56934594/145268093-ffb81741-b6ed-404d-b7f7-124fe0c214ed.png" alt="drawing" width="200"/>

# References
Not Applicable.

**Comment by PranshuPandya** [comment]
I have revert the ui of the app so if this still happens with that ui than raise a new issue I am closing this for now.
