### ISSUE TITLE
Links for linkedin and github are still not working.

### ISSUE THREAD

**Issue by letsintegreat** [PranshuPandya/locus-stolker-app#46]
#3 is still reproducible.
Check the video here: https://imgur.com/a/A0aYaFB

When clicked on any of the links, "Something went wrong!" is shown.

**Comment by letsintegreat** [comment]
I'd like to work on this issue.

**Comment by Pranav108** [comment]
It is working totally fine in my emulator as well as in my physical device.
Did you tried to open any other link in your emulator🤔.

**Comment by letsintegreat** [comment]
@Pranav108 Yeah, links from another project (chapter3-book-renting-app) are working fine on my emulator, but I haven't checked it on my physical device, let me do that.

If it is working for you, there must be some mistake at my end.

**Comment by letsintegreat** [comment]
@Pranav108 It worked fine on my physical device, there seems to be some issue with my emulator~
