### ISSUE TITLE
bug with the searching

### ISSUE THREAD

**Issue by PranshuPandya** [PranshuPandya/locus-stolker-app#5]
In the search menu when you type first charcter the list is not being shown while after you type second or more character the list is shown . So solve this bug so that list is shown after adding one charcter also.

**Comment by Pranav108** [comment]
Sounds new to me but will love to solve it, can I work on it?

**Comment by PranshuPandya** [comment]
ya go ahead

**Comment by Pranav108** [comment]
Yesterday I also noticed this issue but when I started working on it today, it was working fine😶.
![search_bar_functanality](https://user-images.githubusercontent.com/56934594/144710396-64420141-d595-451f-8d40-8704445902ac.gif)

**Comment by Pranav108** [comment]
@PranshuPandya can you please look into it ,it's already been 3 days.

**Comment by PranshuPandya** [comment]
yeah right
