### ISSUE TITLE
issue with about and logout button

### ISSUE THREAD

**Issue by PranshuPandya** [PranshuPandya/locus-stolker-app#8]
The about and logout buttons are working only when youn click on the text and not on the area outside the text of the button. the buttons can be found on the group screen by clicking on the pop up menu button.

**Comment by Jenilnagrecha** [comment]
I am interested in fixing it.

**Comment by PranshuPandya** [comment]
ok go ahead.

**Comment by Jenilnagrecha** [comment]
since my PR is merged and issue is solved you may close it
